import {
    Tailwind,
    React as ReactIcon,
    Node,
    Canva,
    Python,
    Javascript,
    Java,
    Leetcode,
    Css,
    Html,
    Shad,
    Framer,
    Mongo,
    Express,
    Socket,
    PostSql,
    Cpanel,
    Github,
    MySql,
    Git,
    OpenAi,
    Actions,
    Vite,
    Vscode,
    Render,
    Jwt,
    Rest,
    Router,
    Axios
} from './index';

export const Icons: Record<string, React.FC<React.SVGProps<SVGSVGElement>>> = {
    react: ReactIcon,
    tailwind: Tailwind,
    css: Css,
    javascript: Javascript,
    html: Html,
    'framer-motion': Framer,
    canva: Canva,
    express: Express,
    java: Java,
    'node-js': Node,
    python: Python,
    shadcn: Shad,
    'mongo-db': Mongo,
    postgresql: PostSql,
    'socket-io': Socket,
    github: Github,
    cpanel: Cpanel,
    'mysql': MySql,
    git: Git,
    'open-ai': OpenAi,
    'github-actions': Actions,
    vite: Vite,
    vscode: Vscode,
    render: Render,
    jwt: Jwt,
    rest: Rest,
    'react-router': Router,
    axios: Axios,
    leetcode: Leetcode
    // Optional: aliases for your existing icons

};
